In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r"C:\Users\29rah\Documents\ShiRaKu_Personal\Git\Karnataka-Paddy-Analysis\NIC_Kar_Paddy.csv")

In [3]:
df = df.drop('SlNo', axis = 1)
df

,District Name,Kharif_AreaBefore bund correction factor,Kharif_AreaAfter bund correction factor,Kharif_Yield,Kharif_Production,Rabi_AreaBefore bund correction factor,Rabi_AreaAfter bund correction factor,Rabi_Yield,Rabi_Production,Summer_AreaBefore bund correction factor,Summer_AreaAfter bund correction factor,Summer_Yield,Summer_Production,All Seasons_AreaBefore bund correction factor,All Seasons_Area After bund correction factor,All Seasons_Yield,All Seasons_Production
0,BAGALKOTE,35,34,4159,143,0,0,0,0,3,3,4616,14,38,37,4195,156
1,BENGALURU - URBAN,202,198,4242,840,0,0,0,0,74,73,4616,335,276,270,4342,1174
2,BENGALURU - RURAL,162,159,3372,535,0,0,0,0,31,30,4616,140,193,189,3572,676
3,BELAGAVI,57100,55958,4643,259813,0,0,0,0,173,170,4616,783,57273,56128,4643,260596
4,BALLARI,105169,103066,5853,603243,0,0,0,0,75422,73914,5327,393738,180591,176979,5633,996981
5,BIDAR,614,602,2511,1511,0,0,0,0,124,122,4616,561,738,723,2865,2072
6,VIJAYAPURA,128,125,4643,582,0,0,0,0,34,33,4616,154,162,159,4637,736
7,CHAMARAJANAGAR,8330,8163,4208,34352,826,809,3304,2675,1362,1335,3493,4662,10518,10308,4044,41688
8,CHICKBALLAPUR,3630,3557,4288,15254,0,0,0,0,3223,3159,4451,14059,6853,6716,4365,29313
9,CHIKMAGALUR,10739,10524,3770,39676,0,0,0,0,331,324,4750,1541,11070,10849,3799,41217
10,CHITRADURGA,1248,1223,2822,3451,0,0,0,0,335,328,2771,910,1583,1551,2811,4361
11,DAKSHINA KANNADA,6264,6139,4400,27010,1127,1104,4180,4617,7,7,4616,32,7398,7250,4367,31659
12,DAVANAGERE,67792,66436,5641,374766,0,0,0,0,55009,53909,5029,271107,122801,120345,5367,645874
13,DHARWAD,13049,12788,1896,24246,0,0,0,0,34,33,4616,154,13083,12821,1903,24400
14,GADAG,3545,3474,3372,11715,0,0,0,0,2705,2651,3329,8825,6250,6125,3353,20540
15,KALBURGI,8906,8728,6029,52620,0,0,0,0,4574,4483,5027,22534,13480,13210,5689,75154
16,HASSAN,35115,34413,3480,119756,0,0,0,0,255,250,3400,850,35370,34663,3479,120606
17,HAVERI,31710,31076,2507,77907,0,0,0,0,11546,11315,4616,52230,43256,42391,3070,130137
18,KODAGU,20205,19801,3966,78530,0,0,0,0,8,8,3069,24,20213,19809,3966,78554
19,KOLAR,3939,3860,3034,11712,0,0,0,0,1141,1118,5543,6198,5080,4978,3598,17910
20,KOPPAL,59129,57946,5022,291007,0,0,0,0,49229,48244,4929,237797,108358,106191,4980,528804
21,MANDYA,56889,55751,4520,251996,412,404,3692,1491,17007,16667,4628,77134,74308,72822,4540,330620
22,MYSURU,81568,79937,4725,377701,0,0,0,0,13811,13535,4323,58511,95379,93471,4667,436211
23,RAICHUR,190638,186825,4678,873968,0,0,0,0,149924,146926,4760,699365,340562,333751,4714,1573334
24,RAMANAGARAM,3035,2974,4206,12510,0,0,0,0,142,139,4086,569,3177,3113,4201,13079
25,SHIVAMOGGA,75138,73635,3967,292111,0,0,0,0,11924,11686,4201,49091,87062,85321,3999,341202
26,TUMAKURU,3050,2989,3616,10808,0,0,0,0,275,270,4418,1191,3325,3259,3682,11999
27,UDUPI,37742,36987,4479,165665,5798,5682,4004,22751,36,35,4616,163,43576,42704,4416,188579
28,UTTARA KANNADA,45408,44500,3278,145870,633,620,3560,2208,407,399,3822,1524,46448,45519,3287,149603
29,YADGIR,97648,95695,5424,519050,569,558,2621,1462,49950,48951,2603,127419,148167,145204,4462,647931
30,State Total,1028127,1007564,4643,4678351,9365,9178,3836,35203,449096,440114,4616,2031613,1486588,1456856,4630,6745166

In [7]:
df = df[~(df['District Name'] == 'State Total')]

In [10]:
df.head()

,District Name,Kharif_AreaBefore bund correction factor,Kharif_AreaAfter bund correction factor,Kharif_Yield,Kharif_Production,Rabi_AreaBefore bund correction factor,Rabi_AreaAfter bund correction factor,Rabi_Yield,Rabi_Production,Summer_AreaBefore bund correction factor,Summer_AreaAfter bund correction factor,Summer_Yield,Summer_Production,All Seasons_AreaBefore bund correction factor,All Seasons_Area After bund correction factor,All Seasons_Yield,All Seasons_Production
0,BAGALKOTE,35,34,4159,143,0,0,0,0,3,3,4616,14,38,37,4195,156
1,BENGALURU - URBAN,202,198,4242,840,0,0,0,0,74,73,4616,335,276,270,4342,1174
2,BENGALURU - RURAL,162,159,3372,535,0,0,0,0,31,30,4616,140,193,189,3572,676
3,BELAGAVI,57100,55958,4643,259813,0,0,0,0,173,170,4616,783,57273,56128,4643,260596
4,BALLARI,105169,103066,5853,603243,0,0,0,0,75422,73914,5327,393738,180591,176979,5633,996981

In [12]:
seasons = ['Kharif', 'Rabi', 'Summer']

seasons_columns = {}

for item in seasons:
    seasons_columns[item] =[
        "District Name",
        f"{item}_AreaBefore bund correction factor",
        f"{item}_AreaAfter bund correction factor",
        f"{item}_Yield",
        f"{item}_Production"
    ]

In [14]:
df.columns = (
                df.columns
                .str.replace("bund correction factor","", regex=False)
                .str.replace("AreaBefore", "AreaBefore", regex= False)
                .str.replace("AreaAfter ", "AreaAfter", regex= False)
                .str.strip()
)